import React from "react";
import { Link, useNavigate } from "react-router-dom";
import RiderNavbar from "../components/RiderNavbar";
import Footer from "../components/Footer";

export default function RiderTermsPage() {
  const navigate = useNavigate();

  return (
    <div className="bg-[#09090B] min-h-screen text-[#F4F4F5] flex flex-col font-sans" style={{ fontFamily: "'Manrope', 'Inter', sans-serif" }}>
      {/* Rider Navbar */}
      <RiderNavbar />

      {/* Dark Orange Header Strip (Zepto Style matching Rider App Theme) */}
      <div className="bg-[#18181B] border-b border-[#27272A] text-white py-8 sm:py-12 px-4 text-center space-y-4 shadow-md">
        <h1 className="text-2xl sm:text-4xl font-extrabold tracking-tight underline underline-offset-8 decoration-[#F97316]">
          Filcarts Delivery Partner Terms of Use
        </h1>

        {/* Quick Switcher */}
        <div className="pt-2 flex justify-center items-center gap-2">
          <button
            className="bg-[#F97316] text-white font-extrabold text-xs px-4 py-1.5 rounded-full shadow-xs cursor-default"
          >
            Terms of Use
          </button>
          <button
            onClick={() => navigate("/privacy")}
            className="bg-[#27272A] hover:bg-[#3F3F46] text-[#D4D4D8] font-extrabold text-xs px-4 py-1.5 rounded-full transition-all cursor-pointer"
          >
            Privacy Policy
          </button>
        </div>
      </div>

      {/* Clean Zepto-Style Document Body */}
      <main className="max-w-4xl mx-auto px-6 sm:px-8 py-10 space-y-6 flex-1 w-full text-left">
        
        {/* Meta Version & Last Updated */}
        <div className="space-y-1 text-xs text-[#A1A1AA] italic font-semibold border-b border-[#27272A] pb-4">
          <p>Version 1.0</p>
          <p>Last updated: 20 August 2026</p>
        </div>

        {/* Legal Electronic Record Statement */}
        <p className="text-xs sm:text-sm text-[#D4D4D8] leading-relaxed font-medium">
          This document is an electronic record published in accordance with the provisions of the Information Technology Act, 2000 and the rules thereunder, as applicable and amended from time to time. This document is generated by a computer system and does not require any physical or digital signatures.
        </p>

        {/* Section 1 */}
        <div className="space-y-2 pt-2">
          <h2 className="text-base sm:text-lg font-bold text-white flex items-center gap-2">
            <span className="text-[#F97316]">1.</span> Delivery Partner Onboarding & Eligibility
          </h2>
          <p className="text-xs sm:text-sm text-[#A1A1AA] leading-relaxed font-medium">
            By registering as a delivery partner on the <strong>Filcarts Rider App</strong>, you represent that you are at least 18 years of age, hold a valid Indian Driving License (for motorized vehicles), Aadhaar Card, PAN Card, and active bank account for payouts.
          </p>
          <p className="text-xs sm:text-sm text-[#A1A1AA] leading-relaxed font-medium">
            Riders operate as independent gig contractors and not as direct salaried employees of Filcarts Technologies Pvt Ltd.
          </p>
        </div>

        {/* Section 2 */}
        <div className="space-y-2 pt-2">
          <h2 className="text-base sm:text-lg font-bold text-white flex items-center gap-2">
            <span className="text-[#F97316]">2.</span> Rider Earnings, Surge & Payout Settlement
          </h2>
          <p className="text-xs sm:text-sm text-[#A1A1AA] leading-relaxed font-medium">
            Payouts are calculated based on completed order distance, order volume incentives, peak hour surge bonuses, and rain allowances as displayed in your Rider App dashboard.
          </p>
          <p className="text-xs sm:text-sm text-[#A1A1AA] leading-relaxed font-medium">
            Weekly earnings are deposited directly into your registered bank account on a fixed weekly settlement cycle without unauthorized deductions.
          </p>
        </div>

        {/* Section 3 */}
        <div className="space-y-2 pt-2">
          <h2 className="text-base sm:text-lg font-bold text-white flex items-center gap-2">
            <span className="text-[#F97316]">3.</span> Flexible Shift Slots & Order Dispatch
          </h2>
          <p className="text-xs sm:text-sm text-[#A1A1AA] leading-relaxed font-medium">
            Riders enjoy complete flexibility to choose active login shifts, preferred delivery zones, and online hours.
          </p>
          <p className="text-xs sm:text-sm text-[#A1A1AA] leading-relaxed font-medium">
            Once an order is accepted, you agree to fulfill the delivery promptness within the target SLA time while following traffic safety rules.
          </p>
        </div>

        {/* Section 4 */}
        <div className="space-y-2 pt-2">
          <h2 className="text-base sm:text-lg font-bold text-white flex items-center gap-2">
            <span className="text-[#F97316]">4.</span> Insurance, Safety & Emergency Helpline
          </h2>
          <p className="text-xs sm:text-sm text-[#A1A1AA] leading-relaxed font-medium">
            All active Filcarts delivery partners receive 100% complimentary accident and medical hospitalization insurance coverage while on an active delivery shift.
          </p>
          <p className="text-xs sm:text-sm text-[#A1A1AA] leading-relaxed font-medium">
            In case of vehicle breakdown or road emergency, riders can tap 'SOS Emergency Support' in the app to dispatch backup rider assistance instantly.
          </p>
        </div>

        {/* Section 5 */}
        <div className="space-y-2 pt-2">
          <h2 className="text-base sm:text-lg font-bold text-white flex items-center gap-2">
            <span className="text-[#F97316]">5.</span> Equipment & Hygiene Guidelines
          </h2>
          <p className="text-xs sm:text-sm text-[#A1A1AA] leading-relaxed font-medium">
            Riders agree to use the thermal insulated delivery bag provided by Filcarts to ensure fresh grocery and food temperature preservation during transit.
          </p>
        </div>

        {/* Section 6 */}
        <div className="space-y-2 pt-2 pb-6">
          <h2 className="text-base sm:text-lg font-bold text-white flex items-center gap-2">
            <span className="text-[#F97316]">6.</span> Governing Law & Jurisdiction
          </h2>
          <p className="text-xs sm:text-sm text-[#A1A1AA] leading-relaxed font-medium">
            These Delivery Partner Terms shall be governed by and construed in accordance with the laws of India. Courts in Gurgaon / New Delhi shall have exclusive jurisdiction over any legal disputes.
          </p>
        </div>

      </main>

      {/* Rider Footer */}
      <Footer />
    </div>
  );
}
