import React from "react";
import { Link, useNavigate } from "react-router-dom";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export default function TermsPage() {
  const navigate = useNavigate();

  return (
    <div className="bg-[#FFFCF5] min-h-screen text-[#17231A] flex flex-col font-sans" style={{ fontFamily: "'Manrope', 'Inter', sans-serif" }}>
      {/* Navbar */}
      <Navbar searchPlaceholder="Search terms of use..." />

      {/* Dark Green Header Strip (Zepto Style) */}
      <div className="bg-[#166534] text-white py-8 sm:py-12 px-4 text-center space-y-4 shadow-md">
        <h1 className="text-2xl sm:text-4xl font-extrabold tracking-tight underline underline-offset-8 decoration-emerald-400">
          FillCarts Terms of Use
        </h1>

        {/* Quick Switcher */}
        <div className="pt-2 flex justify-center items-center gap-2">
          <button
            className="bg-white/20 text-white font-extrabold text-xs px-4 py-1.5 rounded-full border border-white/30 backdrop-blur-xs cursor-default"
          >
            Terms of Use
          </button>
          <button
            onClick={() => navigate("/privacy")}
            className="bg-emerald-950/60 hover:bg-emerald-950 text-emerald-100 font-extrabold text-xs px-4 py-1.5 rounded-full transition-all cursor-pointer"
          >
            Privacy Policy
          </button>
        </div>
      </div>

      {/* Clean Zepto-Style Document Body */}
      <main className="max-w-4xl mx-auto px-6 sm:px-8 py-10 space-y-6 flex-1 w-full text-left">
        
        {/* Meta Version & Last Updated */}
        <div className="space-y-1 text-xs text-slate-500 italic font-semibold border-b border-slate-200/80 pb-4">
          <p>Version 1.0</p>
          <p>Last updated: 20 August 2026</p>
        </div>

        {/* Legal Electronic Record Statement */}
        <p className="text-xs sm:text-sm text-slate-700 leading-relaxed font-medium">
          This document is an electronic record and published in accordance with the provisions of the Information Technology Act, 2000 and the rules thereunder, as applicable and amended from time to time. This document is generated by a computer system and does not require any physical or digital signatures.
        </p>

        {/* Section 1 */}
        <div className="space-y-2 pt-2">
          <h2 className="text-base sm:text-lg font-bold text-[#17231A]">
            1. Terms of Use & Eligibility
          </h2>
          <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-medium">
            By downloading, browsing, or placing orders on the <strong>FillCarts</strong> platform, you agree to be bound by these Terms of Use. You represent that you are at least 18 years of age and legally competent to enter into a contract under the Indian Contract Act, 1872.
          </p>
        </div>

        {/* Section 2 */}
        <div className="space-y-2 pt-2">
          <h2 className="text-base sm:text-lg font-bold text-[#17231A]">
            2. Customer Account & Registration
          </h2>
          <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-medium">
            Customer registration requires a valid Indian mobile number and SMS OTP verification. You are responsible for maintaining the confidentiality of your login OTPs and account activity.
          </p>
          <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-medium">
            You agree to provide accurate delivery addresses and contact details. FillCarts reserves the right to suspend accounts that engage in fraudulent behavior or order abuse.
          </p>
        </div>

        {/* Section 3 */}
        <div className="space-y-2 pt-2">
          <h2 className="text-base sm:text-lg font-bold text-[#17231A]">
            3. Ordering, Pricing & 15-30 Min Delivery
          </h2>
          <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-medium">
            All prices are displayed in Indian Rupees (₹) inclusive of applicable taxes. Delivery fees and handling charges are itemized clearly on the checkout page before payment.
          </p>
          <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-medium">
            Estimated delivery times (15–30 minutes) are targets based on distance and traffic conditions. Delivery times may vary during heavy weather or peak traffic hours.
          </p>
        </div>

        {/* Section 4 */}
        <div className="space-y-2 pt-2">
          <h2 className="text-base sm:text-lg font-bold text-[#17231A]">
            4. Cancellations & Refund Policy
          </h2>
          <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-medium">
            Orders can be cancelled free of cost before store acceptance. If cancelled after store acceptance, cancellation charges equal to the order amount may apply.
          </p>
          <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-medium">
            Refunds for missing, damaged, or spoiled items are initiated immediately upon verification and credited to your original payment method within 3 to 5 business days.
          </p>
        </div>

        {/* Section 5 */}
        <div className="space-y-2 pt-2">
          <h2 className="text-base sm:text-lg font-bold text-[#17231A]">
            5. Intellectual Property Rights
          </h2>
          <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-medium">
            All trademarks, software code, UI designs, logos, and graphics on FillCarts are the exclusive property of FillCarts Technologies Pvt Ltd. Unauthorized copying, scraping, or reproduction is strictly prohibited.
          </p>
        </div>

        {/* Section 6 */}
        <div className="space-y-2 pt-2 pb-6">
          <h2 className="text-base sm:text-lg font-bold text-[#17231A]">
            6. Limitation of Liability & Governing Law
          </h2>
          <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-medium">
            These Terms of Use shall be governed by and construed in accordance with the laws of India. Courts in Gurgaon / New Delhi, India shall have exclusive jurisdiction over any legal disputes.
          </p>
        </div>

      </main>

      {/* Footer */}
      <Footer />
    </div>
  );
}
