export const SEED_PRODUCTS = [
  // Grocery
  {
    productId: "grocery-0",
    name: "Fortune Royal Basmati Rice 5kg",
    categoryKey: "grocery",
    categoryName: "Grocery",
    price: 349,
    mrp: 420,
    rating: 4.8,
    store: "Fresh Mart",
    tags: ["bestseller", "staple"],
    keywords: ["rice", "basmati", "chawal", "rce", "basmat"],
    unit: "5 kg",
    inStock: true,
    countInStock: 60,
    description: "Premium aged royal basmati rice with slender aromatic grains.",
  },
  {
    productId: "grocery-1",
    name: "Tata Sampann Toor Dal 1kg",
    categoryKey: "grocery",
    categoryName: "Grocery",
    price: 159,
    mrp: 185,
    rating: 4.7,
    store: "Daily Needs Express",
    tags: ["protein"],
    keywords: ["dal", "toor", "arhar", "pulses"],
    unit: "1 kg",
    inStock: true,
    countInStock: 80,
    description: "Unpolished, naturally nutrient-rich toor dal.",
  },
  {
    productId: "grocery-2",
    name: "Fortune Refined Sunflower Oil 1L",
    categoryKey: "grocery",
    categoryName: "Grocery",
    price: 135,
    mrp: 160,
    rating: 4.6,
    store: "Fresh Mart",
    tags: ["oil"],
    keywords: ["oil", "tel", "cooking oil", "sunflower"],
    unit: "1 L",
    inStock: true,
    countInStock: 100,
    description: "Light and healthy cooking oil enriched with vitamins.",
  },
  {
    productId: "grocery-3",
    name: "Madhur Pure Sugar 1kg",
    categoryKey: "grocery",
    categoryName: "Grocery",
    price: 48,
    mrp: 55,
    rating: 4.5,
    store: "Daily Needs Express",
    tags: ["sweet"],
    keywords: ["sugar", "cheeni", "shakkar", "sugr"],
    unit: "1 kg",
    inStock: true,
    countInStock: 120,
    description: "Sulphur-free, refined sparkling white sugar crystals.",
  },
  {
    productId: "grocery-4",
    name: "Aashirvaad Shuddh Chakki Atta 5kg",
    categoryKey: "grocery",
    categoryName: "Grocery",
    price: 235,
    mrp: 270,
    rating: 4.9,
    store: "Fresh Mart",
    tags: ["bestseller"],
    keywords: ["atta", "aata", "wheat", "flour", "chapti"],
    unit: "5 kg",
    inStock: true,
    countInStock: 75,
    description: "100% pure whole wheat flour for soft and fluffy rotis.",
  },
  {
    productId: "grocery-5",
    name: "Tata Salt Vacuum Evaporated 1kg",
    categoryKey: "grocery",
    categoryName: "Grocery",
    price: 28,
    mrp: 30,
    rating: 4.8,
    store: "Daily Needs Express",
    tags: ["essential"],
    keywords: ["salt", "namak", "tata salt"],
    unit: "1 kg",
    inStock: true,
    countInStock: 150,
    description: "Iodised vacuum evaporated salt for everyday balanced cooking.",
  },
  {
    productId: "grocery-6",
    name: "Red Label Strong Tea Leaves 250g",
    categoryKey: "grocery",
    categoryName: "Grocery",
    price: 140,
    mrp: 160,
    rating: 4.7,
    store: "Fresh Mart",
    tags: ["chai"],
    keywords: ["tea", "chai", "chaipatti", "red label"],
    unit: "250 g",
    inStock: true,
    countInStock: 90,
    description: "Rich and invigorating blend of Assam tea leaves.",
  },
  {
    productId: "grocery-7",
    name: "Thick Poha Flattened Rice 500g",
    categoryKey: "grocery",
    categoryName: "Grocery",
    price: 42,
    mrp: 52,
    rating: 4.6,
    store: "Daily Needs Express",
    tags: ["breakfast"],
    keywords: ["poha", "pohe", "chiwda", "chira"],
    unit: "500 g",
    inStock: true,
    countInStock: 80,
    description: "Clean flattened rice flakes for wholesome morning breakfast.",
  },

  // Fruits & Vegetables
  {
    productId: "fruits-0",
    name: "Farm Fresh Bananas (Robusta) 1 dozen",
    categoryKey: "fruits",
    categoryName: "Fruits & Vegetables",
    price: 58,
    mrp: 70,
    rating: 4.8,
    store: "Green Leaf Organics",
    tags: ["fresh", "fruit"],
    keywords: ["banana", "bananas", "kela", "bnana", "bana"],
    unit: "12 pcs",
    inStock: true,
    countInStock: 50,
    description: "Naturally ripened sweet Robusta bananas from local farms.",
  },
  {
    productId: "fruits-1",
    name: "Crispy Red Washington Apples 1kg",
    categoryKey: "fruits",
    categoryName: "Fruits & Vegetables",
    price: 189,
    mrp: 220,
    rating: 4.9,
    store: "Green Leaf Organics",
    tags: ["fresh", "imported"],
    keywords: ["apple", "apples", "seb", "aple", "apple"],
    unit: "1 kg",
    inStock: true,
    countInStock: 40,
    description: "Sweet, crunchy and juicy red apples packed with fiber.",
  },
  {
    productId: "fruits-2",
    name: "Fresh Red Onions 1kg",
    categoryKey: "fruits",
    categoryName: "Fruits & Vegetables",
    price: 32,
    mrp: 45,
    rating: 4.5,
    store: "Fresh Mart",
    tags: ["veggie"],
    keywords: ["onion", "onions", "pyaaz", "pyaj", "onin"],
    unit: "1 kg",
    inStock: true,
    countInStock: 100,
    description: "Firm and pungent red onions essential for Indian curries.",
  },
  {
    productId: "fruits-3",
    name: "Ripe Local Tomatoes 1kg",
    categoryKey: "fruits",
    categoryName: "Fruits & Vegetables",
    price: 28,
    mrp: 40,
    rating: 4.6,
    store: "Green Leaf Organics",
    tags: ["veggie"],
    keywords: ["tomato", "tomatoes", "tamatar", "tomamto", "tomto", "tomat"],
    unit: "1 kg",
    inStock: true,
    countInStock: 90,
    description: "Plump red tomatoes picked fresh at peak ripeness.",
  },
  {
    productId: "fruits-4",
    name: "Organic Potatoes (Aalu) 1kg",
    categoryKey: "fruits",
    categoryName: "Fruits & Vegetables",
    price: 26,
    mrp: 35,
    rating: 4.7,
    store: "Fresh Mart",
    tags: ["veggie"],
    keywords: ["potato", "potatoes", "aalu", "alo", "patato"],
    unit: "1 kg",
    inStock: true,
    countInStock: 120,
    description: "Farm-grade earthy potatoes ideal for boiling and frying.",
  },
  {
    productId: "fruits-5",
    name: "Seedless Green Grapes 500g",
    categoryKey: "fruits",
    categoryName: "Fruits & Vegetables",
    price: 95,
    mrp: 120,
    rating: 4.8,
    store: "Green Leaf Organics",
    tags: ["fruit"],
    keywords: ["grapes", "angoor", "grape"],
    unit: "500 g",
    inStock: true,
    countInStock: 35,
    description: "Crisp and refreshing seedless green table grapes.",
  },
  {
    productId: "fruits-6",
    name: "Fresh Green Spinach Bunch (Palak)",
    categoryKey: "fruits",
    categoryName: "Fruits & Vegetables",
    price: 24,
    mrp: 30,
    rating: 4.6,
    store: "Green Leaf Organics",
    tags: ["leafy"],
    keywords: ["spinach", "palak", "green veggie"],
    unit: "1 bunch",
    inStock: true,
    countInStock: 40,
    description: "Tender iron-rich hydroponic spinach leaves.",
  },
  {
    productId: "fruits-7",
    name: "Crunchy Carrots (Gajar) 500g",
    categoryKey: "fruits",
    categoryName: "Fruits & Vegetables",
    price: 38,
    mrp: 50,
    rating: 4.7,
    store: "Fresh Mart",
    tags: ["veggie"],
    keywords: ["carrot", "carrots", "gajar", "gajr"],
    unit: "500 g",
    inStock: true,
    countInStock: 60,
    description: "Sweet orange carrots great for salads, soups, and halwa.",
  },

  // Dairy
  {
    productId: "dairy-0",
    name: "Amul Taaza Toned Fresh Milk 1L",
    categoryKey: "dairy",
    categoryName: "Dairy",
    price: 54,
    mrp: 56,
    rating: 4.9,
    store: "Fresh Mart",
    tags: ["daily"],
    keywords: ["milk", "doodh", "dudh", "milck", "amul milk"],
    unit: "1 L",
    inStock: true,
    countInStock: 100,
    description: "Pasteurised toned milk with essential nutrients and calcium.",
  },
  {
    productId: "dairy-1",
    name: "Mother Dairy Fresh Curd (Dahi) 400g",
    categoryKey: "dairy",
    categoryName: "Dairy",
    price: 35,
    mrp: 40,
    rating: 4.8,
    store: "Daily Needs Express",
    tags: ["curd"],
    keywords: ["curd", "dahi", "yoghurt", "yogurt", "crd"],
    unit: "400 g",
    inStock: true,
    countInStock: 70,
    description: "Creamy set curd prepared from wholesome pasteurised milk.",
  },
  {
    productId: "dairy-2",
    name: "Amul Fresh Soft Paneer 200g",
    categoryKey: "dairy",
    categoryName: "Dairy",
    price: 92,
    mrp: 105,
    rating: 4.9,
    store: "Fresh Mart",
    tags: ["protein"],
    keywords: ["paneer", "panir", "pner", "cottage cheese"],
    unit: "200 g",
    inStock: true,
    countInStock: 50,
    description: "Super soft and fresh cottage cheese blocks.",
  },
  {
    productId: "dairy-3",
    name: "Amul Salted Butter 100g",
    categoryKey: "dairy",
    categoryName: "Dairy",
    price: 58,
    mrp: 62,
    rating: 4.9,
    store: "Daily Needs Express",
    tags: ["butter"],
    keywords: ["butter", "makhan", "amul butter"],
    unit: "100 g",
    inStock: true,
    countInStock: 80,
    description: "Classic delicious salted butter made with pure milk fat.",
  },
  {
    productId: "dairy-4",
    name: "Processed Cheese Slices 200g (10 Slices)",
    categoryKey: "dairy",
    categoryName: "Dairy",
    price: 145,
    mrp: 165,
    rating: 4.7,
    store: "Fresh Mart",
    tags: ["cheese"],
    keywords: ["cheese", "chese", "cheese slice"],
    unit: "10 slices",
    inStock: true,
    countInStock: 45,
    description: "Individually wrapped creamy cheese slices for burgers and toasts.",
  },
  {
    productId: "dairy-5",
    name: "Pure Cow Desi Ghee 500ml",
    categoryKey: "dairy",
    categoryName: "Dairy",
    price: 385,
    mrp: 430,
    rating: 4.9,
    store: "Fresh Mart",
    tags: ["ghee"],
    keywords: ["ghee", "ghi", "desi ghee", "cow ghee"],
    unit: "500 ml",
    inStock: true,
    countInStock: 40,
    description: "Traditional aromatic golden cow ghee.",
  },
  {
    productId: "dairy-6",
    name: "Spiced Masala Buttermilk (Chaas) 200ml",
    categoryKey: "dairy",
    categoryName: "Dairy",
    price: 15,
    mrp: 18,
    rating: 4.6,
    store: "Daily Needs Express",
    tags: ["drink"],
    keywords: ["buttermilk", "chaas", "chach", "masala chaas"],
    unit: "200 ml",
    inStock: true,
    countInStock: 90,
    description: "Cooling spiced buttermilk with mint and cumin flavours.",
  },

  // Bakery
  {
    productId: "bakery-0",
    name: "English Oven 100% Brown Bread 400g",
    categoryKey: "bakery",
    categoryName: "Bakery",
    price: 45,
    mrp: 50,
    rating: 4.8,
    store: "City Artisan Bakery",
    tags: ["healthy"],
    keywords: ["bread", "bred", "brown bread", "pav"],
    unit: "400 g",
    inStock: true,
    countInStock: 40,
    description: "Soft sliced brown bread made from 100% whole wheat.",
  },
  {
    productId: "bakery-1",
    name: "Fresh Flaky Butter Croissant (2 pcs)",
    categoryKey: "bakery",
    categoryName: "Bakery",
    price: 99,
    mrp: 120,
    rating: 4.9,
    store: "City Artisan Bakery",
    tags: ["artisan"],
    keywords: ["croissant", "crosant", "bakery"],
    unit: "2 pcs",
    inStock: true,
    countInStock: 25,
    description: "Golden flaky layered butter croissants baked fresh daily.",
  },
  {
    productId: "bakery-2",
    name: "Rich Double Chocolate Chip Muffin",
    categoryKey: "bakery",
    categoryName: "Bakery",
    price: 65,
    mrp: 80,
    rating: 4.7,
    store: "City Artisan Bakery",
    tags: ["sweet"],
    keywords: ["muffin", "moffin", "cake", "cupcake"],
    unit: "1 pc",
    inStock: true,
    countInStock: 30,
    description: "Moist chocolate muffin loaded with rich cocoa and choc chips.",
  },
  {
    productId: "bakery-3",
    name: "Multigrain Seeded Health Bread",
    categoryKey: "bakery",
    categoryName: "Bakery",
    price: 55,
    mrp: 65,
    rating: 4.8,
    store: "City Artisan Bakery",
    tags: ["healthy"],
    keywords: ["bread", "multigrain bread"],
    unit: "400 g",
    inStock: true,
    countInStock: 35,
    description: "Nutritious artisanal loaf topped with sunflower and flax seeds.",
  },
  {
    productId: "bakery-4",
    name: "Soft Milk Bun Pack (4 pcs)",
    categoryKey: "bakery",
    categoryName: "Bakery",
    price: 35,
    mrp: 40,
    rating: 4.6,
    store: "City Artisan Bakery",
    tags: ["pav"],
    keywords: ["bun", "pav", "buns", "burger bun"],
    unit: "4 pcs",
    inStock: true,
    countInStock: 50,
    description: "Fluffy sweet milk buns perfect for sliders and breakfast.",
  },
  {
    productId: "bakery-5",
    name: "Handcrafted Butter Cookies 200g",
    categoryKey: "bakery",
    categoryName: "Bakery",
    price: 120,
    mrp: 150,
    rating: 4.8,
    store: "City Artisan Bakery",
    tags: ["cookies"],
    keywords: ["cookie", "cookies", "biscuit", "biscuits"],
    unit: "200 g",
    inStock: true,
    countInStock: 40,
    description: "Melt-in-mouth handcrafted cookies made with pure butter.",
  },

  // Pharmacy
  {
    productId: "pharmacy-0",
    name: "Dolo 650 Paracetamol Tablets (Strip of 15)",
    categoryKey: "pharmacy",
    categoryName: "Pharmacy",
    price: 32,
    mrp: 35,
    rating: 4.9,
    store: "City Care Meds",
    tags: ["fever"],
    keywords: ["dolo", "paracetamol", "fever", "tablet", "medicine", "dawa"],
    unit: "15 tablets",
    inStock: true,
    countInStock: 100,
    description: "Effective paracetamol tablets for fever and pain relief.",
  },
  {
    productId: "pharmacy-1",
    name: "Limcee Vitamin C Chewable Tablets 500mg",
    categoryKey: "pharmacy",
    categoryName: "Pharmacy",
    price: 25,
    mrp: 28,
    rating: 4.8,
    store: "City Care Meds",
    tags: ["immunity"],
    keywords: ["limcee", "vitamin c", "vitamin", "tablets"],
    unit: "15 tablets",
    inStock: true,
    countInStock: 90,
    description: "Tasty orange flavoured chewable vitamin C immunity booster.",
  },
  {
    productId: "pharmacy-2",
    name: "Dettol Instant Hand Sanitizer 200ml",
    categoryKey: "pharmacy",
    categoryName: "Pharmacy",
    price: 95,
    mrp: 110,
    rating: 4.7,
    store: "City Care Meds",
    tags: ["hygiene"],
    keywords: ["sanitizer", "hand sanitizer", "dettol"],
    unit: "200 ml",
    inStock: true,
    countInStock: 80,
    description: "Kills 99.9% germs without water in an instant.",
  },
  {
    productId: "pharmacy-3",
    name: "Fast Read Infrared Digital Thermometer",
    categoryKey: "pharmacy",
    categoryName: "Pharmacy",
    price: 499,
    mrp: 750,
    rating: 4.6,
    store: "City Care Meds",
    tags: ["device"],
    keywords: ["thermometer", "fever meter", "digital thermometer"],
    unit: "1 unit",
    inStock: true,
    countInStock: 20,
    description: "Accurate non-contact infrared thermometer with LCD backlight.",
  },
  {
    productId: "pharmacy-4",
    name: "3-Ply Protective Face Masks (Pack of 10)",
    categoryKey: "pharmacy",
    categoryName: "Pharmacy",
    price: 69,
    mrp: 100,
    rating: 4.7,
    store: "City Care Meds",
    tags: ["mask"],
    keywords: ["mask", "masks", "face mask"],
    unit: "10 pcs",
    inStock: true,
    countInStock: 120,
    description: "Breathable 3-layer protective masks with elastic ear loops.",
  },

  // Food
  {
    productId: "food-0",
    name: "Classic Crispy Veg Burger",
    categoryKey: "food",
    categoryName: "Food",
    price: 89,
    mrp: 120,
    rating: 4.7,
    store: "Local Kitchens Express",
    tags: ["fastfood"],
    keywords: ["burger", "bourger", "veg burger"],
    unit: "1 pc",
    inStock: true,
    countInStock: 50,
    description: "Crispy herb potato patty topped with fresh lettuce and sauces.",
  },
  {
    productId: "food-1",
    name: "Paneer Tikka Roll",
    categoryKey: "food",
    categoryName: "Food",
    price: 119,
    mrp: 150,
    rating: 4.8,
    store: "Local Kitchens Express",
    tags: ["snack"],
    keywords: ["roll", "paneer roll", "kathi roll"],
    unit: "1 roll",
    inStock: true,
    countInStock: 40,
    description: "Spiced chargrilled paneer cubes wrapped in a flaky paratha.",
  },
  {
    productId: "food-2",
    name: "Cheesy Margherita Pizza 8 inch",
    categoryKey: "food",
    categoryName: "Food",
    price: 199,
    mrp: 250,
    rating: 4.9,
    store: "Local Kitchens Express",
    tags: ["pizza"],
    keywords: ["pizza", "piza", "pzza", "cheesy pizza"],
    unit: "8 inch",
    inStock: true,
    countInStock: 30,
    description: "Fresh tomato concasse, basil leaves, and 100% pure mozzarella.",
  },
  {
    productId: "food-3",
    name: "Hyderabadi Veg Dum Biryani",
    categoryKey: "food",
    categoryName: "Food",
    price: 179,
    mrp: 220,
    rating: 4.8,
    store: "Local Kitchens Express",
    tags: ["biryani"],
    keywords: ["biryani", "biriyani", "biryani rice"],
    unit: "1 portion",
    inStock: true,
    countInStock: 35,
    description: "Fragrant basmati rice slow cooked on dum with marinated vegetables.",
  },
  {
    productId: "food-4",
    name: "Crispy Butter Masala Dosa",
    categoryKey: "food",
    categoryName: "Food",
    price: 99,
    mrp: 130,
    rating: 4.9,
    store: "Local Kitchens Express",
    tags: ["southindian"],
    keywords: ["dosa", "dosai", "masala dosa"],
    unit: "1 pc",
    inStock: true,
    countInStock: 45,
    description: "Golden crispy crepe stuffed with spiced potato masala.",
  },

  // Pet Care
  {
    productId: "pet-0",
    name: "Pedigree Adult Chicken & Vegetables 3kg",
    categoryKey: "pet",
    categoryName: "Pet Care",
    price: 649,
    mrp: 720,
    rating: 4.8,
    store: "Pet Planet",
    tags: ["dog"],
    keywords: ["dog food", "pedigree", "kutta food", "dog"],
    unit: "3 kg",
    inStock: true,
    countInStock: 25,
    description: "Complete and balanced dry dog food for active adult dogs.",
  },
  {
    productId: "pet-1",
    name: "Whiskas Ocean Fish Dry Cat Food 1.2kg",
    categoryKey: "pet",
    categoryName: "Pet Care",
    price: 399,
    mrp: 450,
    rating: 4.7,
    store: "Pet Planet",
    tags: ["cat"],
    keywords: ["cat food", "whiskas", "billi food", "cat"],
    unit: "1.2 kg",
    inStock: true,
    countInStock: 30,
    description: "Crunchy pockets filled with real fish protein for healthy cats.",
  },
  {
    productId: "pet-2",
    name: "Clumping Odor Control Cat Litter 5kg",
    categoryKey: "pet",
    categoryName: "Pet Care",
    price: 349,
    mrp: 420,
    rating: 4.6,
    store: "Pet Planet",
    tags: ["hygiene"],
    keywords: ["cat litter", "litter", "pet litter"],
    unit: "5 kg",
    inStock: true,
    countInStock: 25,
    description: "High absorption clumping bentonite clay cat litter.",
  },

  // Home Essentials
  {
    productId: "home-0",
    name: "Vim Lemon Dishwash Gel 500ml",
    categoryKey: "home",
    categoryName: "Home Essentials",
    price: 105,
    mrp: 120,
    rating: 4.8,
    store: "Daily Needs Express",
    tags: ["cleaning"],
    keywords: ["vim", "dishwash", "bartan soap", "liquid soap"],
    unit: "500 ml",
    inStock: true,
    countInStock: 60,
    description: "Concentrated lime dishwashing gel with powerful grease cleaners.",
  },
  {
    productId: "home-1",
    name: "Lizol Disinfectant Floor Cleaner 1L",
    categoryKey: "home",
    categoryName: "Home Essentials",
    price: 185,
    mrp: 210,
    rating: 4.9,
    store: "Fresh Mart",
    tags: ["floor"],
    keywords: ["lizol", "floor cleaner", "pocha"],
    unit: "1 L",
    inStock: true,
    countInStock: 70,
    description: "Floral scented floor cleaner removing tough stains and 99.9% germs.",
  },
  {
    productId: "home-2",
    name: "Surf Excel Easy Wash Liquid 1L",
    categoryKey: "home",
    categoryName: "Home Essentials",
    price: 215,
    mrp: 245,
    rating: 4.9,
    store: "Fresh Mart",
    tags: ["laundry"],
    keywords: ["surf", "surf excel", "detergent", "kapde soap"],
    unit: "1 L",
    inStock: true,
    countInStock: 65,
    description: "Super effective liquid laundry detergent for machine & bucket wash.",
  },

  // Personal Care
  {
    productId: "personal-0",
    name: "Himalaya Purifying Neem Face Wash 100ml",
    categoryKey: "personal",
    categoryName: "Personal Care",
    price: 125,
    mrp: 140,
    rating: 4.8,
    store: "Daily Needs Express",
    tags: ["skincare"],
    keywords: ["facewash", "face wash", "himalaya", "neem"],
    unit: "100 ml",
    inStock: true,
    countInStock: 50,
    description: "Herbal face wash with neem and turmeric for clear, pimple-free skin.",
  },
  {
    productId: "personal-1",
    name: "Dove Intense Repair Shampoo 340ml",
    categoryKey: "personal",
    categoryName: "Personal Care",
    price: 285,
    mrp: 340,
    rating: 4.9,
    store: "Fresh Mart",
    tags: ["haircare"],
    keywords: ["shampoo", "sampoo", "dove", "hair wash"],
    unit: "340 ml",
    inStock: true,
    countInStock: 55,
    description: "Deep nourishing shampoo formulated with keratin repair actives.",
  },
  {
    productId: "personal-2",
    name: "Colgate Strong Teeth Toothpaste 150g",
    categoryKey: "personal",
    categoryName: "Personal Care",
    price: 92,
    mrp: 105,
    rating: 4.8,
    store: "Daily Needs Express",
    tags: ["dental"],
    keywords: ["toothpaste", "paste", "colgate", "brush"],
    unit: "150 g",
    inStock: true,
    countInStock: 90,
    description: "Amino Shakti formula for 2x stronger teeth and cavity protection.",
  },

  // Electronics
  {
    productId: "electronics-0",
    name: "Fast Charging Type-C USB Cable 1m",
    categoryKey: "electronics",
    categoryName: "Electronics",
    price: 149,
    mrp: 299,
    rating: 4.6,
    store: "Tech Hub Express",
    tags: ["cable"],
    keywords: ["cable", "usb", "type c", "charger cable", "iphne"],
    unit: "1 m",
    inStock: true,
    countInStock: 40,
    description: "Durable braided nylon 3A fast charging data cable.",
  },
  {
    productId: "electronics-1",
    name: "In-Ear Bass Wired Earphones 3.5mm",
    categoryKey: "electronics",
    categoryName: "Electronics",
    price: 249,
    mrp: 499,
    rating: 4.5,
    store: "Tech Hub Express",
    tags: ["audio"],
    keywords: ["earphones", "headphone", "earphone", "handsfree"],
    unit: "1 pc",
    inStock: true,
    countInStock: 35,
    description: "Comfortable dynamic bass earphones with in-line microphone.",
  },
  {
    productId: "electronics-2",
    name: "10000mAh Fast Power Bank Dual USB",
    categoryKey: "electronics",
    categoryName: "Electronics",
    price: 899,
    mrp: 1499,
    rating: 4.8,
    store: "Tech Hub Express",
    tags: ["power"],
    keywords: ["powerbank", "power bank", "battery"],
    unit: "1 unit",
    inStock: true,
    countInStock: 25,
    description: "Slim portable lithium-polymer power bank with dual USB fast output.",
  },
  {
    productId: "electronics-3",
    name: "Philips 9W Cool Day White LED Bulb",
    categoryKey: "electronics",
    categoryName: "Electronics",
    price: 99,
    mrp: 140,
    rating: 4.8,
    store: "Tech Hub Express",
    tags: ["lighting"],
    keywords: ["bulb", "led", "light bulb", "philips"],
    unit: "1 pc",
    inStock: true,
    countInStock: 80,
    description: "Energy efficient B22 LED bulb with bright glare-free illumination.",
  }
];
